# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_auto_20191021_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default='10-21-2019'),
        ),
    ]
