# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0003_auto_20191021_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history_total_price',
        ),
    ]
