# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(),
        ),
    ]
