# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0002_auto_20191018_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
