# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0003_auto_20191018_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 20, 21, 14, 846879, tzinfo=utc)),
        ),
    ]
