# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0004_auto_20191018_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 22, 4, 28, 360961)),
        ),
    ]
