# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0007_auto_20191018_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(default='10/19/2019'),
        ),
    ]
