# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0008_auto_20191019_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='changezz',
            field=models.CharField(default='add', max_length=255),
            preserve_default=False,
        ),
    ]
