# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_maker', '0009_show_changezz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateTimeField(default='10/20/2019'),
        ),
    ]
