# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_message', models.TextField(default='No Quote')),
                ('author_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_quote_id', models.ManyToManyField(related_name='quotes_id', to='quote_dash_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='likers_quote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_id', to='quote_dash_app.Quote'),
        ),
    ]
