# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0002_auto_20191022_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='one_like_check',
            field=models.BooleanField(default=False),
        ),
    ]
