# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0004_auto_20191022_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='one_like_check',
        ),
        migrations.AddField(
            model_name='like',
            name='likers_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users_like_id', to='quote_dash_app.User'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='users_quote_id',
        ),
        migrations.AddField(
            model_name='quote',
            name='users_quote_id',
            field=models.ManyToManyField(default=0, related_name='quotes_id', to='quote_dash_app.User'),
        ),
    ]
