# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0005_auto_20191022_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='users_quote_id',
        ),
        migrations.AddField(
            model_name='quote',
            name='users_quote_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_id', to='quote_dash_app.User'),
        ),
    ]
