# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManyPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(related_name='publishers', to='users_app.ManyBook')),
            ],
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='OneAuthor',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='OneBook',
        ),
    ]
